# Generated by Django 2.2.5 on 2019-09-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='user_saved',
            field=models.ManyToManyField(related_name='saved', to='roulette.User'),
        ),
    ]
